"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-17 19:53:28.108464

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('representative_post_id', sa.BigInteger(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_job'), 'job_runs', ['job'], unique=False)
    op.create_table('llm_spend',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('markets',
    sa.Column('ticker', sa.String(length=128), nullable=False),
    sa.Column('event_ticker', sa.String(length=128), nullable=True),
    sa.Column('series_ticker', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('rules_summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yes_price', sa.Integer(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_markets_close_time'), 'markets', ['close_time'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('feed_url', sa.String(length=512), nullable=True),
    sa.Column('handle', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('unsub_token', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('unsub_token')
    )
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=True),
    sa.Column('author_handle', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_post_source_external')
    )
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    op.create_table('post_markets',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('price_at_link', sa.Integer(), nullable=True),
    sa.Column('price_1h', sa.Integer(), nullable=True),
    sa.Column('price_24h', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['markets.ticker'], ),
    sa.PrimaryKeyConstraint('post_id', 'ticker')
    )
    # ### end Alembic commands ###
    # No ANN index here on purpose. An IVFFlat index built on an empty table
    # trains its centroids on no data, and the resulting degenerate lists can
    # make a similarity search return wrong rows or none at all -- silently,
    # since nothing in the suite exercises it (the test schema comes from
    # create_all, not from these migrations). At the catalog size this
    # product works with (~10k markets) an exact sequential scan is
    # single-digit milliseconds and it is *correct*. An ivfflat or hnsw
    # index belongs in a later migration, created after the tables have been
    # backfilled with real embeddings.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_markets')
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('subscribers')
    op.drop_table('sources')
    op.drop_index(op.f('ix_markets_close_time'), table_name='markets')
    op.drop_table('markets')
    op.drop_table('llm_spend')
    op.drop_index(op.f('ix_job_runs_job'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_table('clusters')
    # ### end Alembic commands ###
